name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21
          cache: sbt
      - name: Check format
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
