name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.14
      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Check format
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
